sudo: required
services:
   - docker

before_install:
   - docker build -t tamnd/docker-react -f Dockerfile.dev .

scripts:
   - docker run -e CI=true tamnd/docker-react npm run  

deploy:
   provider: elasticbeanstalk
   region: "us-east-2"
   app: "docker-react"
   env: "DockerReact-env"
   bucket-name: "elasticbeanstalk-us-east-2-248355644819"
   bucket-path: "docker-react"
   on:
     branch: master
   access_key_id: $AWS_ACCESS_KEY
   secret_access_key: $AWS_SECRET_KEY
